### ISSUE TITLE
 Help~

### ISSUE THREAD

**Issue by dingding552** [Zeng-WH/Prompt-Tuning#1]

**Comment by Zeng-WH** [comment]
> 嗷～我在看相关的代码想实现一下遇到了问题，看到大佬已经implemented T5 好激动呀 想请教一下，找不到邮件，在这里冒昧打扰了。 我微信:ding3398 邮件:[ding14552@gmail.com](mailto:ding14552@gmail.com) 希望能联系上 呜呜 打扰了

哈哈 可以可以
