### ISSUE TITLE
请问T5 decoder的输入前面是也加上了prompt embedding吗

### ISSUE THREAD

**Issue by luxuantao** [Zeng-WH/Prompt-Tuning#2]
如题，盼回复，谢谢！

**Comment by Zeng-WH** [comment]
是的

**Comment by luxuantao** [comment]
> 是的

非常感谢！

**Comment by luxuantao** [comment]
貌似原论文是只在encoder上加了prompt？

**Comment by luxuantao** [comment]
貌似原论文是只在encoder上做了prompt?

**Comment by Zeng-WH** [comment]
对，原文只在encoder上加了prompt。但我们发现encoder和decoder都加prompt可能会提升表现（prefix-tuning会在encoder和decoder都加prefix）。您可以做消融实验测试一下。

**Comment by luxuantao** [comment]
> 对，原文只在encoder上加了prompt。但我们发现encoder和decoder都加prompt可能会提升表现（prefix-tuning会在encoder和decoder都加prefix）。您可以做消融实验测试一下。

嗯嗯，了解了，再次感谢！
